language: perl
perl:
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - cpanm English Exporter File::Slurp FindBin JSON::PP Test::More Test::Most Test::FailWarnings
script:
  - "prove -lr t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
